### ISSUE TITLE
Non instant mixing 

### ISSUE THREAD

**Issue by 6102bitcoin** [nopara73/Dumplings#1]
Describing non instant mixing of tx outputs as inefficient is inaccurate.

**Comment by nopara73** [comment]
What do you mean by inefficient?

For accuracy, it barely has any errors in case of Samuri as if a user doesn't mix a TX0 output or put it into another TX0, then that's a coin intended to be mixed, yet it wasn't for some reason. For Wasabi/Otheri CoinJoins it's still fairly accurate for the similar reasons, but it's more tricky because you can't know for sure if the change comes from a mixed UTXO or not, but it is unlikely to do so. I've done Wasabi only stats on it previously where I looked at some other things, too, you may want to check that out:

![image](https://user-images.githubusercontent.com/9156103/82651669-c072fc80-9c1c-11ea-8fa1-42c7eee986f1.png)

https://github.com/nopara73/WasabiCjEfficiency#wasabi-inefficiency

**Comment by 6102bitcoin** [comment]
You are making implicit assumptions in your characterisation of something as inefficient.

The design of whirlpool is such that it doesn't matter if it takes some time for your coins to enter the pool. You leave your node on and mixing and eventually all coins mix. 

By using the term 'inefficient' you are assuming that instantaneous mixing is nececcary which is not the case, for whirlpool at least.

**Comment by nopara73** [comment]
There's no time dimension involved. A TX0 output either gets mixed or doesn't.

**Comment by ghost** [comment]
This metric shows a coin that entered a coinjoin ceremony [either input in wasabi cj, or input in tx0], but did not gain any privacy [unmixed change in wasabi, no cj in whirlpool]. `Inefficiency` is a decent name for such a thing.

If your complaint is about the name of a metric, suggest something better, or get over it.

**Comment by 6102bitcoin** [comment]
What does instantaneously have to do with this?

**Comment by nopara73** [comment]
![image](https://user-images.githubusercontent.com/9156103/82738908-851b1f80-9d3b-11ea-87e2-dbbfce487e01.png)


> By using the term 'inefficient' you are assuming that instantaneous mixing is nececcary which is not the case, for whirlpool at least.

**Comment by PulpCattel** [comment]
The misunderstanding is in:
*How many non-mixed bitcoins (CJ change outputs in the case of Otheri and Wasabi and TX0 non-mixed outputs in the case of Samuri) were not instantly mixed.*

Nopara means how much change is created from the CoinJoins; inputs that are not **instantly** mixed but rather have to be mixed later.
He doesn't mean to say that they have to be mixed in the next hour or whatever.

p.s.
the sentence is arguably a bit ambiguous.

**Comment by nopara73** [comment]
Aah, thanks @PulpCattel without you we would've kept talking past each other https://github.com/nopara73/Dumplings/commit/3e1b2cffe9a23742ccb601634f0d72a687d1284f#diff-04c6e90faac2675aa89e2176d2eec7d8
